[package]
name = "first_wgpu_app"
version = "0.0.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }